### ISSUE TITLE
Is there a method analogous to gpioSetTimerFunc () in the pigpiod API?

### ISSUE THREAD

**Issue by JacekRuzyczka** [joan2937/pigpio#231]
I'm migrating an app currently using the pigpio API "directly" to pigpiod, but I can't find a viable replacement for calls like this one:

`gpioSetTimerFunc (4, 500, OnRDSDataTimerElapsed);`

Which pigpiod API method should I use here? Thank you.

**Comment by guymcswain** [comment]
It probably didn't make a lot of sense to implement this API over the socket interface since it really is just a sleep function with a callback.  You could easily do a similar function in your code running remotely.  If you are timing very short delays, you may have to refactor your app to account for network latency.

**Comment by JacekRuzyczka** [comment]
OK, thank you for the hint, even if it's a pity that many pigpio utility methods also appear in pdif2 (even if some of them don't really need a socket interface) whereas this one does not. Continuing to use gpioSetTimerFunc() does not really help as it needs a gpioInitialise() call beforehand, which in turn requires root priviliges, and this is why I am now switching to pdif2.

Maybe I will find a C/C++ solution, which provedes callbacks at timed intervals is such a convenient way as gpioSetTimerFunc() does. :-/
