### ISSUE TITLE
Baud Rate

### ISSUE THREAD

**Issue by cc96cc** [joan2937/pigpio#263]
How can I set a much higher baud rate using pigpio.bb_spi_open?
I would like baud rates greater than 50 MHz.

**Comment by guymcswain** [comment]
Not much higher than maybe 50KHz.  This comes from my experience using bit-bang serial.  The maximum sample rate for bb I/O is 1MHz so theoretically, the highest signal rate would be 500KHz.  However, due to sampling jitter, created by high traffic on the internal DMA channels, to get a reliable (error-free) signal you need to be well under 100MHz.

**Comment by cc96cc** [comment]
Ok is there any other way to get the baud rate up to 50 MHz?

**Comment by joan2937** [comment]
@guymcswain is correct.

There is no way 50 MHz will work on the Pi.  I think even the Pi's UART hardware is limited to 4 MHz.
