### ISSUE TITLE
error while loading shared libraries: ligpigpio.so on 64-bit RPi4

### ISSUE THREAD

**Issue by FilipSLO** [joan2937/pigpio#450]
Hi joan2937.

First thanks for your great library. I used it for years from RPi3 onwards on Raspbian.
But on new install of [Mageia linux](https://www.mageia.org/) unfortunately it seems that  #284 doesn't help. At least I have this error on RPi4 4G:
`$ sudo ./x_pigpio
./x_pigpio: error while loading shared libraries: libpigpio.so.1: cannot open shared object file: No such file or directory
`
Same problem when I try to load pigpiod.

No recognizable warnings in build log.

Any idea?

**Comment by FilipSLO** [comment]
I would appreciate stated reason for closing.

**Comment by guymcswain** [comment]
Yes, sorry.  We don’t have access to all the various os environments nor the time to test.  The os supported  for this library is the raspberry pi os.

**Comment by FilipSLO** [comment]
Thanks for explanation. I might try again some day.

**Comment by ifactorial0** [comment]
I had the same problem. My research resulted in the following understanding:

I am on Ubuntu 22.04 LTS. To install pigpio first I cloned the repo to a local folder. Inside that folder, I ran the following commands to build and install pigpio:

- `cmake -B build`
- `cmake --build build`
- `sudo cmake --build build --target install`

This worked. After using these commands I could write my own C++ program with CMake, `find_package(pigpio)` and `target_link_libraries(prog PRIVATE pigpio)` worked just fine and the code compiled. However, when I tried to run the program I got the same error as you `libpigpio.so.1: cannot open shared object file: No such file or directory)`

Here is what is happening: CMake is able to find and compile the pigpio library just fine. But since we installed pigpio ourselves, it is installed under `/usr/local/` which is a directory that will by default not be searched by the program loader. So, the code compiles fine, but when you try to run it, it just can't find the pigpio library. To fix this, after installing pigpio with the commands above, you have to run `ldconfig` afterwards. This will create all required links and the program will run correctly.

**Comment by FilipSLO** [comment]
Thanks for posting your findings!

Maybe pigpio can be changed to search also /usr/local/.
