### ISSUE TITLE
Rising edge vs falling edge description for gpioSetAlertFunc() and gpioSetISRFunc()

### ISSUE THREAD

**Issue by lebarsfa** [joan2937/pigpio#497]
There might be something confusing if we read:
https://github.com/joan2937/pigpio/blob/c33738a320a3e28824af7807edafda440952c05d/pigpio.h#L918-L919
https://github.com/joan2937/pigpio/blob/c33738a320a3e28824af7807edafda440952c05d/pigpio.h#L1423-L1424
https://github.com/joan2937/pigpio/blob/c33738a320a3e28824af7807edafda440952c05d/pigpio.h#L1532-L1560

Sometimes rising corresponds to 0 while falling is 1, sometimes it is the inverse. Maybe a warning could be added to the documentation to underline the different definitions.

**Comment by guymcswain** [comment]
> 
#define RISING_EDGE  0 
#define FALLING_EDGE 1 

These defines have names that are consistent with their meaning despite the assigned value.  As a programmer I don't care what its value it as long as RISING_EDGE is consistent with the expected behavior.

`level`, in the context you highlight, refers to a change in level.  So if a change in level occurs and its resulting value is 0 then it must have been a falling edge.
